#!/bin/bash

#rename multiple files
function supermv () {
        FILES="$2"
        PATTERN="$1"
        for i in $FILES; do N=$( echo "$i" | sed "$PATTERN" ); mv "$i" "$N"; done
}

# Make box around text @climagic
function box() { t="$1xxxx";c=${2:-=}; echo ${t//?/$c}; echo "$c $1 $c"; echo ${t//?/$c}; }

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LS_COLORS=$LS_COLORS"*.C=1;35:*.root=1;36:*.py=1;31"
export LC_ALL="en_US.UTF-8"
export EDITOR='nvim'

# node nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
