#!/bin/bash

#rename multiple files
function supermv () {
        FILES="${@:2}"
        PATTERN="$1"
        for i in $~FILES; do N=$( echo "$i" | sed "$PATTERN" ); mv "$i" "$N"; done
}

# Make box around text @climagic
function box() { t="$1xxxx";c=${2:-=}; echo ${t//?/$c}; echo "$c $1 $c"; echo ${t//?/$c}; }

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LS_COLORS=$LS_COLORS"*.C=1;35:*.root=1;36:*.py=1;31"
export LC_ALL="en_US.UTF-8"
export EDITOR='nvim'

# node nvm
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# fzf
if command -v bat &> /dev/null
then
        # Preview file content using bat (https://github.com/sharkdp/bat)
        export FZF_CTRL_T_OPTS="
          --preview 'bat -n --color=always {}'
          --bind 'ctrl-/:change-preview-window(down|hidden|)'"
fi

if command -v fd &> /dev/null
then
        export FZF_DEFAULT_COMMAND='fd --type file'
        export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"

if command -v pyenv &> /dev/null
then
  export PYENV_ROOT=$HOME/.pyenv
  export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
fi

export PATH="$HOME"/phys_utils:"$HOME"/phys_utils/fermilab:"$HOME"/phys_utils/bnl:"$HOME"/.local/bin:$PATH

gbatdiff() {
    git diff --name-only --relative $1 | xargs bat --diff
}
