# Path to your oh-my-zsh installation.
export ZSH=/nashome/b/bnayak/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="nitish_rr"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git history zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# User configuration

# aliases
if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

#util functions
if [ -f ~/.utils ]; then
    . ~/.utils
fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=39'
#syntax-highlighting
source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#vim mode
source $ZSH_CUSTOM/plugins/zsh-vimto/zsh-vimto.zsh

#fzf
if [ -f ~/.fzf.zsh ]; then
    . ~/.fzf.zsh
fi
